# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "🧪 CI: Development"

on:
  pull_request:
    branches: ["main"]
    paths:
      - "tui/**"
      - ".github/workflows/tui-ci-development.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_ORGANIZATION: 105637539410
      GCP_ORGANIZATION_JSON: ${{ github.workspace }}/google/tui/domain/organization.json
      GITHUB_ORG: ${{ github.repository_owner }}
      GITHUB_REPO: ${{ github.event.repository.name }}
      PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER}}
      WORKLOAD_IDENTITY_POOL: ${{ secrets.WORKLOAD_IDENTITY_POOL }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      WIF_PRINCIPAL: ${{ secrets.WIF_PRINCIPAL }}
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      REPO_PRINCIPAL: ${{ secrets.REPO_PRINCIPAL }}

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Install Dependencies
        run: |
          tui/scripts/install.sh

      - name: Lint with flake8, black, isort
        run: |
          tui/scripts/lint.sh

      - name: Test with pytest
        run: |
          tui/scripts/test.sh
